services:
  web:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
  app:
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - internal
  db:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bhp_project
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - internal
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - internal

networks:
  internal:
    driver: bridge



# services:
#   nginx:
#     container_name: nginx
#     image: nginx:alpine
#     volumes:
#       - ./src:/var/www/html
#       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#     ports:
#       - '8080:80'
#     networks:
#       - internal
#   php:
#     container_name: php
#     build:
#       dockerfile: ./docker/php/Dockerfile
#     ports:
#       - '9000:9000'
#     networks:
#       - internal
#   db:
#     container_name: mysql
#     image: mysql:8.0
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: bhp_project
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#     ports:
#       - "3307:3306"
#     volumes:
#       - ./docker/mysql:/var/lib/mysql
#     networks:
#       - internal
# networks:
#   internal:
#     driver: bridge


# networks:
#   slim:
#     driver: bridge

# services:
#   php:
#     container_name: php
#     build:
#       context: ./docker/php
#       dockerfile: Dockerfile
#     ports:
#       - '9000:9000'
#     volumes:
#       - .:/var/www/html
#     networks:
#       - slim
#   nginx:
#     container_name: nginx
#     image: nginx:stable-alpine
#     ports:
#       - '8080:80'
#     volumes:
#       - .:/var/www/html
#       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - php
#     networks:
#       - slim
